### ISSUE TITLE
is-plain-object -> is-plain-obj

### ISSUE THREAD

**Issue by kasperlewau** [SamVerschueren/obj-clean#3]
I don't suppose I could convince you to switch from is-plain-object to is-plain-obj (prior to the upcoming ES2015 rewrite)? 

As part of my (somewhat an*l) byte-hunt, I found that is-plain-obj had a smaller footprint than is-plain-object, and assisted a great deal in deduping the amount of dependencies rolled out for a distribution build (obviously that depends entirely on the dependency graph of each project). 

I'm currently using [kasperlewau/obj-clean/tree/replace-is-plain-object](https://github.com/kasperlewau/obj-clean/tree/replace-is-plain-object) to satisfy this 'need'.

**Comment by SamVerschueren** [comment]
Oh good catch! Totally, all in for using that one!

**Comment by kasperlewau** [comment]
Sa-weet! :smile:

**Comment by SamVerschueren** [comment]
Can you do a PR?

**Comment by kasperlewau** [comment]
Sure thing. On my way back home, wont be long :)
